apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-be
  labels:
    app: k8s-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-be
  template:
    metadata:
      labels:
        app: k8s-be
    spec:
      containers:
        - name: k8s-be
          image: service-owl:5000/k8s-owl-be:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8008
            - name: ws-port
              containerPort: 8009
