apiVersion: v1
kind: Service
metadata:
  name: k8s-owl-be
  labels:
    name: k8s-owl-be
spec:
  ports:
    - name: http-port
      port: 8008
      targetPort: http-port
      protocol: TCP
      nodePort: 30808
    - name: ws-port
      port: 8009
      targetPort: ws-port
      protocol: TCP
      nodePort: 30809
  externalIPs:
    - 192.168.120.135
  selector:
    app: k8s-be
  type: NodePort
